name: {{PROJECT_NAME}}
recipe: wordpress
config:
  webroot: ./
  via: {{SERVER_TYPE}}
  php: {{PHP_VERSION}}
  xdebug: true
  config:
    php: config/php.ini
services:
  node:
    type: node:{{NODE_VERSION}}
  cache:
    type: redis
    portforward: 6379
  appserver:
    build_as_root:
      - "apt-get update"
    run:
      - "bash scripts/wp-setup.sh"
    env_file:
      - .env
logs:
  appserver:
    - /var/log/nginx
    - /var/log/php
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  php:
    service: appserver
  wp:
    service: appserver
    cmd: wp
  redis-cli:
    service: cache
